title: Watashiwa sei kai no jo osuma desu!
author: Becky Blue
email: thebeckyblue@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This right here is the most awesome discription you will ever read!

# social links

github_username:  BeckerBlue

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima 
